on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PULL }}

      - name: Go Build && Binary Upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AUTOMATION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AUTOMATION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: | 
          startDir=`pwd`

          #install fyne-cross
          git clone https://github.com/fyne-io/fyne-cross.git
          cd fyne-cross
          go build .
          mv fyne-cross /tmp
          cd ..  

          #fyne commands
          go get

          #windows/linux/darwin
          /tmp/fyne-cross windows -app-id EW.Messenger -image ghcr.io/ktraister/fyne_builder_win:latest
          /tmp/fyne-cross linux -app-id EW.Messenger -image ghcr.io/ktraister/fyne_builder_nix:latest

          #extract binaries to an easier spot to work with
          unzip ./fyne-cross/dist/windows-amd64/ew_messenger.exe.zip -d .
          tar -xf ./fyne-cross/dist/linux-amd64/ew_messenger.tar.xz --directory .
          mv ./usr/local/bin/ew_messenger .
          #create our zip files
          zip ew_messenger_win.zip ew_messenger.exe "shortcuts/Endless Waltz Messenger.lnk" shortcuts/Icon.ico
          zip ew_messenger_nix.zip ew_messenger "shortcuts/endlesswaltz.desktop" Icon.png

          aws s3 cp ew_messenger_nix.zip s3://endless-waltz-xyz-downloads
          aws s3 cp ew_messenger_win.zip s3://endless-waltz-xyz-downloads

          cd $startDir
          aws s3 cp scripts/win_install.ps1 s3://endless-waltz-xyz-downloads
          aws s3 cp scripts/linux_install.sh s3://endless-waltz-xyz-downloads
          
      - name: Release for private repo
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "ew_messenger*"
          token: ${{secrets.RELEASE_TOKEN}}

      - name: Release for public repo
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "ew_messenger*"
          token: ${{secrets.RELEASE_TOKEN}}
          repo: endless_waltz_public
