on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build
        run: | 
          #install fyne-cross
          git clone https://github.com/fyne-io/fyne-cross.git
          cd fyne-cross
          go build .
          mv fyne-cross /tmp

          cd ..  

          #fyne commands
          go get

          #windows/linux/darwin
          /tmp/fyne-cross windows -app-id EW.Messenger
          mv ./fyne-cross/dist/windows-amd64/ew_messenger.exe.zip ./win_ew_messenger.tar.xz

          /tmp/fyne-cross linux -app-id EW.Messenger
          mv ./fyne-cross/dist/linux-amd64/ew_messenger.tar.xz ./nix_ew_messenger.tar.xz

          #ugh why is mac such a pain in the ass!!
          #fyne-cross darwin-sdk-extract --xcode-path /path/to/Command_Line_Tools_for_Xcode_12.5.dmg
          #fyne-cross darwin -app-id EW.Messenger --macosx-sdk-path /full/path/to/SDKs/MacOSX12.5.sdk
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.xz"
