on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PULL }}

      - name: Go Build
        run: | 
          #install fyne-cross
          git clone https://github.com/fyne-io/fyne-cross.git
          cd fyne-cross
          go build .
          mv fyne-cross /tmp

          cd ..  

          #fyne commands
          go get

          #windows/linux/darwin
          /tmp/fyne-cross windows -app-id EW.Messenger -image ghcr.io/ktraister/fyne_builder_win:latest
          /tmp/fyne-cross linux -app-id EW.Messenger -image ghcr.io/ktraister/fyne_builder_nix:latest

          #move the binaries to an easier spot to work with
          mv ./fyne-cross/dist/windows-amd64/ew_messenger.exe.zip ./win_ew_messenger.tar.xz
          mv ./fyne-cross/dist/linux-amd64/ew_messenger.tar.xz ./nix_ew_messenger.tar.xz

          #ugh why is mac such a pain in the ass!!
          #fyne-cross darwin-sdk-extract --xcode-path /path/to/Command_Line_Tools_for_Xcode_12.5.dmg
          #fyne-cross darwin -app-id EW.Messenger --macosx-sdk-path /full/path/to/SDKs/MacOSX12.5.sdk
          
      - name: Release for private repo
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.xz"
          token: ${{secrets.RELEASE_TOKEN}}

      - name: Release for public repo
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.xz"
          token: ${{secrets.RELEASE_TOKEN}}
          repo: endless_waltz_public
