on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  gui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          #test the code
          go test -v -a .

          #test the build
          git clone https://github.com/fyne-io/fyne-cross.git
          cd fyne-cross
          go build .
          mv fyne-cross /tmp
          cd ..  
 
          #windows/linux/darwin
          /tmp/fyne-cross linux -app-id EW.Messenger
